spring:
  application:
    name: cars
  flyway:
    enabled: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cars?allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver