spring:
  application:
    name: cars
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/cars?allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS

stripe:
  test:
    private-key: ${STRIPE_PRIVATE_KEY_TEST}
    payment-url: ${STRIPE_PAYMENT_URL}
    webhook-key: ${STRIPE_WEBHOOK_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
    disable-swagger-default-url: true