spring:
  application:
    name: car-ordering
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/cars?allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
stripe:
  test:
    private-key: ${STRIPE_PRIVATE_KEY_TEST}
    payment-url: ${STRIPE_PAYMENT_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
    disable-swagger-default-url: true